import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Plus, Minus } from 'lucide-react';
import LayoutContainer from './LayoutContainer';

const faqs = [
  {
    question: "Is AI Resume Builder really free to use?",
    answer: "Yes! Our basic plan allows you to create and download one resume for free. We also offer premium plans for users who need unlimited resumes, advanced ATS optimization, and more templates."
  },
  {
    question: "Are the resumes generated by AI ATS-friendly?",
    answer: "Absolutely. Our templates and AI-generated content are designed specifically to pass Applicant Tracking Systems with ease. We use standard fonts and clean layouts that recruiters and software love."
  },
  {
    question: "Can I edit my resume after it's generated?",
    answer: "Yes, you have full control. You can edit every single word, change templates, reorder sections, and refine the AI's suggestions in our intuitive editor."
  },
  {
    question: "How does the AI optimize my bullet points?",
    answer: "Our AI analyzes industry standards and high-performing resumes to suggest impactful action verbs and quantitative results that highlight your achievements effectively."
  },
  {
    question: "Can I download my resume as a PDF?",
    answer: "Yes, all resumes can be downloaded as professional, pixel-perfect PDFs that preserve your chosen design and formatting perfectly."
  }
];

const FAQItem = ({ faq, isOpen, toggle }) => {
  return (
    <div className={`border-b border-white/10 transition-colors ${isOpen ? 'bg-white/[0.02]' : ''}`}>
      <button 
        onClick={toggle}
        className="w-full flex items-center justify-between py-6 px-4 md:px-8 text-left"
      >
        <span className="text-lg font-bold text-white pr-8">{faq.question}</span>
        {isOpen ? (
          <Minus className="w-5 h-5 text-primary flex-shrink-0" />
        ) : (
          <Plus className="w-5 h-5 text-text-muted flex-shrink-0" />
        )}
      </button>

      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <div className="px-4 md:px-8 pb-8 text-text-muted leading-relaxed">
              {faq.answer}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(0);

  return (
    <section id="faq" className="py-24">
      <LayoutContainer className="max-w-4xl">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-outfit font-bold text-white mb-6">Frequently Asked <span className="text-gradient-primary">Questions</span></h2>
          <p className="text-lg text-text-muted">Everything you need to know about our AI resume platform.</p>
        </div>

        <div className="glass-card rounded-3xl overflow-hidden">
          {faqs.map((faq, index) => (
            <FAQItem 
              key={index} 
              faq={faq} 
              isOpen={openIndex === index}
              toggle={() => setOpenIndex(prev => prev === index ? null : index)}
            />
          ))}
        </div>
      </LayoutContainer>
    </section>
  );
};

export default FAQ;
